# Generated by Django 3.0.7 on 2020-06-10 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of User')),
                ('city', models.CharField(max_length=30, verbose_name='City of User')),
                ('street', models.CharField(max_length=60, verbose_name='Street of User')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('purchase_id', models.IntegerField(primary_key=True, serialize=False)),
                ('purchase_timestamp', models.DateTimeField(blank=True, null=True)),
                ('delivery_timestamp', models.DateTimeField(blank=True, null=True)),
                ('delivery_company', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('category_path', models.CharField(max_length=150, verbose_name='Path of categories')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(verbose_name='Related Session ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('VIEW', 'VIEW_PRODUCT'), ('BUY', 'BUY_PRODUCT')], default='VIEW', max_length=20)),
                ('offered_discount', models.IntegerField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kurier.Product')),
                ('purchase_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kurier.Delivery')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kurier.Account')),
            ],
        ),
    ]
